// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVImI_yK_C04pndQOtI1IwTShVocO4OT4',
    appId: '1:820520644149:web:1bfb31b94253160bcc8b7c',
    messagingSenderId: '820520644149',
    projectId: 'sahaya-86dcd',
    authDomain: 'sahaya-86dcd.firebaseapp.com',
    storageBucket: 'sahaya-86dcd.appspot.com',
    measurementId: 'G-LLEMBXEVDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMJoSsVKpGqMbeV5-LYOsWX2Yw57GJC0Y',
    appId: '1:820520644149:android:2c9fee4da9fa3a68cc8b7c',
    messagingSenderId: '820520644149',
    projectId: 'sahaya-86dcd',
    storageBucket: 'sahaya-86dcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDENoFE9c0vdClBRx7fmra7I32y-rekOSA',
    appId: '1:820520644149:ios:8296fdfc978a8910cc8b7c',
    messagingSenderId: '820520644149',
    projectId: 'sahaya-86dcd',
    storageBucket: 'sahaya-86dcd.appspot.com',
    iosBundleId: 'com.example.groupchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDENoFE9c0vdClBRx7fmra7I32y-rekOSA',
    appId: '1:820520644149:ios:8296fdfc978a8910cc8b7c',
    messagingSenderId: '820520644149',
    projectId: 'sahaya-86dcd',
    storageBucket: 'sahaya-86dcd.appspot.com',
    iosBundleId: 'com.example.groupchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVImI_yK_C04pndQOtI1IwTShVocO4OT4',
    appId: '1:820520644149:web:d309e78bf2c2afdfcc8b7c',
    messagingSenderId: '820520644149',
    projectId: 'sahaya-86dcd',
    authDomain: 'sahaya-86dcd.firebaseapp.com',
    storageBucket: 'sahaya-86dcd.appspot.com',
    measurementId: 'G-57H37DRVY8',
  );

}