// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfjk1cZVEqVeXBzLIWQlz7DjXr1faU6Vw',
    appId: '1:7891309513:web:7fdb14d00470664cb6ce18',
    messagingSenderId: '7891309513',
    projectId: 'crud-c9802',
    authDomain: 'crud-c9802.firebaseapp.com',
    storageBucket: 'crud-c9802.appspot.com',
    measurementId: 'G-9F84F3VJ79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTze6ApH9va2zmMns2nOySgP1oInQIpEg',
    appId: '1:7891309513:android:c0c3ace5ba64c01cb6ce18',
    messagingSenderId: '7891309513',
    projectId: 'crud-c9802',
    storageBucket: 'crud-c9802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU50vkiEstnDotvQFStmG6GQsULxTIPHg',
    appId: '1:7891309513:ios:7b63a3889eb741d6b6ce18',
    messagingSenderId: '7891309513',
    projectId: 'crud-c9802',
    storageBucket: 'crud-c9802.appspot.com',
    iosBundleId: 'com.example.crudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU50vkiEstnDotvQFStmG6GQsULxTIPHg',
    appId: '1:7891309513:ios:d234affaed19419fb6ce18',
    messagingSenderId: '7891309513',
    projectId: 'crud-c9802',
    storageBucket: 'crud-c9802.appspot.com',
    iosBundleId: 'com.example.crudFirestore.RunnerTests',
  );
}
